# Generated by Django 2.2.6 on 2020-01-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list', '查看每个表的数据列表页'),), 'verbose_name': '用户信息表：UserProfile', 'verbose_name_plural': '用户信息表：UserProfile'},
        ),
    ]
