# Generated by Django 2.2.6 on 2020-01-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20200104_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list_view', 'kadmin 可以访问表内容'), ('crm_table_list_change', 'kadmin 可以修改表内容'), ('crm_table_list_add_view', 'kadmin 访问数据增加页面'), ('crm_table_list_add', 'kadmin 添加表数据')), 'verbose_name': '用户信息表：UserProfile', 'verbose_name_plural': '用户信息表：UserProfile'},
        ),
    ]
