# Generated by Django 2.2.6 on 2020-01-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20200104_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='crm.Role'),
        ),
    ]
